name: pack-extension
on: workflow-dispatch
jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: get chrome
        run: |
          sudo apt-get install chromium-browser
          chrome --pack-extension=$GITHUB_WORKSPACE
